*** Error: Abaqus Error: Restart of an Abaqus/Standard analysis requires the following files: res, prt, mdl, stt, sim.
The analysis cannot proceed.
*** Error: Abaqus Error: Restart of an Abaqus/Standard analysis requires the following files: res, prt, mdl, stt, sim.
The analysis cannot proceed.
*** Error: Abaqus Error: Restart of an Abaqus/Standard analysis requires the following files: res, prt, mdl, stt, sim.
The analysis cannot proceed.
*** Error: Abaqus Error: Restart of an Abaqus/Standard analysis requires the following files: res, prt, mdl, stt, sim.
The analysis cannot proceed.
*** Error: Abaqus Error: Restart of an Abaqus/Standard analysis requires the following files: res, prt, mdl, stt, sim.
The analysis cannot proceed.
